language: node_js
node_js:
  - "5"
  
before_script:
  - 'if [ "$SEQ_VERSION" ]; then npm install node-sass@$SEQ_VERSION; fi'

env:
  - SASS_VERSION=3.7.0
  - SASS_VERSION=3.6.0
  - SASS_VERSION=3.5.3
